[package]
name = "rox2d"
version = "0.1.0"
edition = "2021"

[lib]
name = "rox2d"

[[example]]
name = "basic"

[dependencies]
glam = "0.22.0"
rand = "0.8.5"

[dev-dependencies]
bevy = "0.9.1"

[profile.dev.package."*"]
# Set optimization level for dependencies to 3
opt-level = 3
